# Generated by Django 4.1.1 on 2022-10-03 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_to_do", models.CharField(max_length=200)),
                ("complete", models.BooleanField(default="False")),
                (
                    "added_time",
                    models.DateTimeField(
                        verbose_name=datetime.datetime(2022, 10, 3, 14, 0, 52, 56821)
                    ),
                ),
            ],
        )
    ]
